AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Scatter Gather

Parameters:
  RawDataBaseName:
    Type: String
    Default: "raw_data_covid_19"
    Description: "Name of the AWS Glue database to contain raw data tables."
  
  S3RawDataLocationURI:
    Type: String
    Default: "s3://covid19-lake/rearc-covid-19-nyt-data-in-usa/json/us-states"
    Description: "S3 location for raw sample data."

Resources:
########################################################
# Glue table
########################################################
  GlueRawDataBase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref RawDataBaseName
        Description: Database Raw Data

  GlueRawDataNYTimesCovidTable:
    Type: 'AWS::Glue::Table'
    Properties: 
      CatalogId: !Ref AWS::AccountId     
      DatabaseName: !Ref GlueRawDataBase
      TableInput: 
        Description: "Raw Data on COVID-19 cases from NY Times at US state level."
        TableType: "EXTERNAL_TABLE"
        Retention: 0
        Name: covid_nytimes_states
        Parameters:
          has_encrypted_data: False
          classification: json
          typeOfData: file
        StorageDescriptor:
          Compressed: False
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          Location: !Ref S3RawDataLocationURI
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          StoredAsSubDirectories: false
          SerdeInfo:
            Parameters: {
              "paths": "date,state,fips,cases,deaths"
            }
            SerializationLibrary: "org.openx.data.jsonserde.JsonSerDe"
          Columns:
            - Type: string
              Name: date
              Comment: "reporting date"
            - Type: string
              Name: state
              Comment: ""
            - Type: string
              Name: fips
              Comment: "FIPS code"
            - Type: bigint
              Name: cases
              Comment: "# confirmed cases"
            - Type: bigint
              Name: deaths
              Comment: "# deaths"

########################################################
# S3 Bucket processed data
########################################################
  ProcessedDataS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join
        - "-"
        - - "scatter-gather-processed-data"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"